#!/usr/bin/env bash
# Writes the clgpt launcher. Lives here rather than inline in install.sh so
# `clgpt update` can refresh it too.
#
# Usage: write-launcher.sh <app-dir> <bin-dir> [bun-path]
set -euo pipefail

CLGPT_DIR="${1:?app dir required}"
BIN_DIR="${2:?bin dir required}"
BUN_BIN="${3:-$(command -v bun)}"
[ -n "$BUN_BIN" ] || { echo "bun not found" >&2; exit 1; }

# Bump when the launcher body changes; clgpt compares it to warn about a stale
# launcher that predates a feature.
LAUNCHER_VERSION=4

mkdir -p "$BIN_DIR"
[ ! -d "$BIN_DIR/clgpt" ] || {
  echo "$BIN_DIR/clgpt is a directory, not a launcher file" >&2
  exit 1
}
TMP_LAUNCHER="$(mktemp "$BIN_DIR/.clgpt-launcher.XXXXXX")"
trap 'rm -f "$TMP_LAUNCHER"' EXIT
{
  printf '%s\n' '#!/usr/bin/env bash'
  printf '# clgpt launcher v%s (generated by scripts/write-launcher.sh)\n' "$LAUNCHER_VERSION"
  printf 'CLGPT_APP_DIR=%q\n' "$CLGPT_DIR"
  printf 'CLGPT_BIN_DIR=%q\n' "$BIN_DIR"
  printf 'CLGPT_BUN_BIN=%q\n' "$BUN_BIN"
  printf 'CLGPT_LAUNCHER_VERSION=%s\n' "$LAUNCHER_VERSION"
  printf '%s\n' 'export CLGPT_APP_DIR CLGPT_BIN_DIR CLGPT_BUN_BIN CLGPT_LAUNCHER_VERSION'
  printf '%s\n' '' \
    '# Corporate TLS: clgpt adds a CA to the OS trust store itself, per request, via' \
    '# CLGPT_CA_BUNDLE — see src/tls.ts. Nothing to set here; NODE_USE_SYSTEM_CA is' \
    '# a no-op on bun, whose default trust set already merges the system roots.' \
    '' \
    '# bun strips a leading "--" before scripts see it — translate it into a' \
    '# sentinel that cli.ts understands as "everything after belongs to claude".' \
    'if [ "${1:-}" = "--" ]; then' \
    '  shift' \
    '  set -- "__clgpt_passthrough__" "$@"' \
    'fi' \
    'exec "$CLGPT_BUN_BIN" run --no-install "$CLGPT_APP_DIR/src/cli.ts" "$@"'
} > "$TMP_LAUNCHER"
chmod +x "$TMP_LAUNCHER"
mv -f "$TMP_LAUNCHER" "$BIN_DIR/clgpt"
trap - EXIT
